# App
spring.application.name=smart-campus

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://smartcampus:Hirunge_db_pw_123@smart-campus.xusjsfm.mongodb.net/?appName=smart-campus
spring.data.mongodb.database=smart_campus

# JWT
jwt.secret=smartcampus-super-secret-key-2026-do-not-share
jwt.expiration=86400000

# Google OAuth
google.client-id=459396940098-10hst6nlcalbp3dv52ev7lg7s029ov49.apps.googleusercontent.com

# Fix Java 23 SSL compatibility
spring.jmx.enabled=false

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

# Server port
server.port=8080

# Logging
logging.level.com.smartcampus=DEBUG

# Serve static files from uploads folder
spring.web.resources.static-locations=classpath:/static/,file:uploads/